# Generated by Django 4.0.5 on 2022-08-08 14:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('content_app', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Blog',
        ),
    ]
